### ISSUE TITLE
blocking read?

### ISSUE THREAD

**Issue by python152** [chrisjbillington/inotify_simple#15]
hi -

Can you provide an example of doing blocking read? this is for the use case of infinite loop and waiting for events. thx

**Comment by python152** [comment]
never mind, I used it wrong, the while True loop is enough.

**Comment by chrisjbillington** [comment]
Yep! You'll want to do a `for` loop over events within a `while True`:
```python
while True:
    for event in inotify.read():
        process_event(event)
```
