### ISSUE TITLE
use ctypes.util.find_library to find libc.so in example.py

### ISSUE THREAD

**Issue by honglei** [chrisjbillington/inotify_simple#20]
Just like:
https://github.com/dwvisser/PyInotify/blob/master/inotify/library.py

**Comment by chrisjbillington** [comment]
Is there a practical downside to hard-coding it, or is this a matter of style?

I believe it's expected that libc will be called `libc.so.6` forever, i.e. that there will never be a `libc.so.7` as libc uses symbol versioning to maintain backward compatibility indefinitely.

**Comment by honglei** [comment]
In some platform，it called libc.so.6.1

Chris Billington <notifications@github.com> 于2020年6月23日周二 下午11:03写道：

**Comment by chrisjbillington** [comment]
That's fine, on those platforms `libc.6.so` will be a symlink to `libc.so.6.1`. Since executables link to exact sonames, these symlinks must exist in order to be able to run executables compiled against a libc called `libc.6.so`.

Is there a platform you know of where inotify_simple can't find libc?

Even though it is a simple change, I lean philosophically toward relying in code on guarantees I'm given, as every bit of code that doubts such guarantees is more surface area for bugs.

**Comment by longbigbeard** [comment]
I have a similar problem，this platforms called libc.so.6.1, 
`

> rc: -1  
> errno: 0  
> Traceback (most recent call last):  
>   File "example.py", line 6, in <module>  
>     inotify = INotify()  
>   File "/home/deepub/likang/inotify_simple/inotify_simple.py", line 94, in __init__  
>     FileIO.__init__(self, _libc_call(_libc.inotify_init1, flags), mode='rb')  
>   File "/home/deepub/likang/inotify_simple/inotify_simple.py", line 40, in _libc_call  
>     raise OSError(errno, strerror(errno))  
> OSError: [Errno 0] Success  

`

Then I changed the code :  **`global _libc; _libc = _libc or CDLL('libc.so.6.1', use_errno=True)`** 

`

> flags: 524288
> rc: -1
> errno: 22
> Traceback (most recent call last):
>   File "example.py", line 6, in <module>
>     inotify = INotify()
>   File "/home/deepub/likang/inotify_simple/inotify_simple.py", line 94, in __init__
>     FileIO.__init__(self, _libc_call(_libc.inotify_init1, flags), mode='rb')
>   File "/home/deepub/likang/inotify_simple/inotify_simple.py", line 40, in _libc_call
>     raise OSError(errno, strerror(errno))
> OSError: [Errno 22] Invalid argument

`
and i found different platforms, using different **CLOEXEC**

**Comment by chrisjbillington** [comment]
@longbigbeard what OS are you on, and what version of `inotfiy_simple`? It doesn't make much sense to me that passing `libc.6.so` would result in `OSError: [Errno 0] Success` - I would have expected something like a `FileNotFoundError` when loading the library. Older versions of `inotfiy_simple` did not set `use_errno=True`, leading to nonsensical errors like `OSError: [Errno 0] Success`. Did you add the `use_errno=True`, or are you on the latest `inotify_simple` where it is already present?

If you added it, then this makes me think that's the change that was relevant, and not the name of the libc shared object.

> and i found different platforms, using different CLOEXEC

Really? Could you show me the contents of `/usr/include/bits/inotify.h` on your system?

I am not under the impression these constants should ever change or that they could be platform specific.

Nonetheless I would be interested to figure out why your system does not like the flags being passed to `inotify_init1`.

**Comment by longbigbeard** [comment]
the latest `inotify_simple` 

> Really? Could you show me the contents of /usr/include/bits/inotify.h on your system?

`
/* Flags for the parameter of inotify_init1.  */  
enum  
  {  
    IN_CLOEXEC  = 010000000,  
#define IN_CLOEXEC IN_CLOEXEC  
    IN_NONBLOCK = 000000004  
#define IN_NONBLOCK IN_NONBLOCK  
  };  
`

**Comment by chrisjbillington** [comment]
Thanks. Wow, you're right. IN_CLOEXEC is different on your system. Mine is `IN_CLOEXEC = 02000000`. That's very strange to me, as code compiled using one of these headers won't work with other systems, and I was under the impression that Linux/glibc are supposed to be backward compatible indefinitely.

What OS are you on?

**Comment by chrisjbillington** [comment]
Ah, are you on a non-x86 system? If so that would explain it. The constants could be architecture-specific, since code compiled on one architecture can't run on other architectures anyway. I discovered this here:

https://github.com/hannobraun/inotify-sys/pull/9

**Comment by chrisjbillington** [comment]
@longbigbeard could you verify that `oct(os.O_CLOEXEC)` and `oct(os.O_NONBLOCK)` agree with the contents of `/bits/inotify.h`? If so, I will have `inotify_simple` use these constants from the interpreter. They agree on x86.

**Comment by chrisjbillington** [comment]
Both issues (finding libc and the architecture-depdendent `IN_CLOEXEC` and `IN_NONBLOCK` constants) should be resolved in 
4e92ebd. Please let me know if issues remain.

**Comment by longbigbeard** [comment]
thanks, my problem has been solved.
it is a non-x86 system with UOS(deepin)
