### ISSUE TITLE
Trying to watch and reload a config file with inotify_simple.

### ISSUE THREAD

**Issue by Wesztman** [chrisjbillington/inotify_simple#24]
Hi!

I´m trying to use inotify_simple to watch a config.ini file and update variables in my main loop if I spot a change in the config file 😄  

I´m however having issues with inotify.read() locking my main loop until a change occurs in my config file 🤔  

```python
def main()

    inotify = INotify()
    watch_flags = flags.MODIFY
    wd = inotify.add_watch(config_file, watch_flags)

    while True:

        for event in inotify.read():
            print(event)
            for flag in flags.from_mask(event.mask):
               print(flag)
               if str(flag) == "flags.MODIFY":
                   # Reload config file
                   print("Reloading configuration file")   
    
        # Code down here only runs after changing config file, and then only run once before getting stuck above again... 
```

Do you have any trick which would solve this? 🤔 

Kind Regards
Carl

**Comment by chrisjbillington** [comment]
You could call read() with timeout=0, then it won't block.

Is your mainloop blocking on something else, e.g. a GUI library's event loop or similar? If so, you can probably register a callback for when the INotify object is readable - it is a file-like object with a regular filedescriptor so should work with anything that expects files. Or if your mainloop is reading other files, it will work with select() etc.

Reading repeatedly with a zero or small timeout is a bit unappealing, so registering a callback or using select() is generally preferable so your app is idle most of the time when nothing is happening.

**Comment by Wesztman** [comment]
I read no other files and my loop is not locked anywhere else, its just a simple state machine for a robot 🤔 im not super used to python. Would you mins putting up a simple example? 😊

**Comment by chrisjbillington** [comment]
Well, what else is your main loop doing?

If it is not doing anything else then blocking on the file would be fine, and presumably the only reason it isn't fine is because your program needs to respond to other things too. If none of those things block, then does that mean your loop just runs as fast as it can?

Typically you would want to use some mechanism to block until there is something to do (either responding to the config file changing, or something else), but which mechanism (callbacks vs select() or something else) depends on what else your program is doing. Would be happy to make suggestions if you share some info about else your mainloop does!

**Comment by Wesztman** [comment]
I havn't gotten that far yet right now, but the idea is to read input on serial bus, do some computations and the set outputs on the serial bus :) you can see the code here https://github.com/Wesztman/brand-pi/blob/main/src/main.py 

I've not commited the notify_simple stuff yet as I couldn´t get it to work :p the sleep is not supposed to be in the final code, it was just to see that the state machine worked as expected :) 

And then the idea was to use inotify_simple to update values from the config file live while the robot is running if there is any changes made in the file :) it´s superb for debugging and testing live (Y)

**Comment by chrisjbillington** [comment]
Cool, so the other thing your program could be waiting for is input from the serial connection. So basically you want a way to wait for *either* serial input *or* inotify events to become available. The way you would typically do this is with `select.select`, something like this (not tested):

```python
import select
import serial
import inotify_simple

inotify = inotify_simple.INotify()
ser_conn = serial.Serial('/dev/ttyUSB0')

while True:
    readable, _, _ = select.select([inotify, ser_conn], [], [])
    if inotify in readable:
        # inotify events available, read them and act on them as needed
        pass
    if ser_conn in readable:
        # serial data has arrived, read it and respond as needed
        pass
        
```

Then your program will spend most of its time blocked on the `select()` call until there is something for it to do. `select()` has a timeout parameter to stop it blocking forever, in case you also want to do things when idle.

**Comment by Wesztman** [comment]
Ahh nice! Thanks! :) Will try it out! <3

**Comment by Wesztman** [comment]
Do I need to clear the "readable" in some way after acting on them? 🤔 Right now I get stuck in the if statement for "inotify in readable" indefinitely after making the first file change after starting my program.

**Comment by chrisjbillington** [comment]
Yes, you would clear the state by reading all available data :).

Edit: actually, I suppose you're implying you've done that? If so, I wouldn't have expected the inotify filedescriptor to still be readable afterward.

**Comment by Wesztman** [comment]
Nhaa I wouldn´t say that, I´ve just made a logging.info("Config file changed") in the if statement :p how would you do a "correct" reading?

EDIT:
I printed the "readable" list and it seems to be stuck on 

`[<_io.FileIO name=3 mode='rb' closefd=True>]`

EDIT2: 
Worth noting that I went a little bit different with 

```
    inotify = INotify()
    watch_flags = flags.MODIFY
    wd = inotify.add_watch(config_file, watch_flags)
```
In my initialization
and 
```
        readable, _, _ = select.select([wd], [], [])
        if wd in readable:
            # Update log level if needed
            logging.info("Config file changed")
```
In my loop 🤔 
Because I thought I had more control over that, maybe that´s what´s messing it up 🤔

**Comment by chrisjbillington** [comment]
You'll need to read the events from the inotify filedescriptor:
```python
for event in inotify.read():
    pass
```

Then there should be nothing left to read and `select()` should block.

Also, you do need to be passing the inotify object to `select()`, not the watch descriptor. The watch descriptor is only relevant for interpreting information in the events, and for removing the watch later. The filedescripor you are interested in reading (and waiting on) is the one associated with the `INotify()` object - this is the 'file' you are reading inotify events from, that the kernel is sending you.

**Comment by Wesztman** [comment]
Ahh perfect, now it works like a charm! :) Thanks for all the help and patience! <3 <3 

**Final code:**

```
import os
import select
from inotify_simple import INotify, flags

current_folder = os.path.dirname(os.path.abspath(__file__))
config_file = os.path.join(current_folder, "config.ini")

inotify = INotify()
watch_flags = flags.MODIFY
wd = inotify.add_watch(config_file, watch_flags)

while True:
        readable, _, _ = select.select([inotify], [], [])

        if inotify in readable:
            for event in inotify.read():
                for flag in flags.from_mask(event.mask):
                    print("Config file changed")
                    # Do something
```

EDIT:
Did not know about select, that´s super handy for alot of stuff, thanks for the lesson (Y)

**Comment by chrisjbillington** [comment]
Great, you're welcome! Glad it's working.
