### ISSUE TITLE
Slightly confused by inotify closing my watches afer each use...

### ISSUE THREAD

**Issue by pootle** [chrisjbillington/inotify_simple#29]
I'm basically using the same example code in your readme, but I'm running it in a loop to monitor for ongoing changes.

But after a CLOSE_WRITE  event, when the next event happens, I get an IGNORE when the file is closed and I have to create a new watch.....

    watch is 1
    at   6.51
         Event(wd=1, mask=8, cookie=0, name='')
          flags.CLOSE_WRITE
    at  11.93
         Event(wd=1, mask=32768, cookie=0, name='')
          flags.IGNORED
    Naughty!!!
    at  11.93
         Event(wd=2, mask=8, cookie=0, name='')
          flags.CLOSE_WRITE

**Comment by pootle** [comment]
Here's the source:

#!/usr/bin/env python
        
        from inotify_simple import INotify, flags
        import pathlib as pl
        import time
        
        if __name__ == '__main__':
            inmgr = INotify()
            p1=pl.Path('testd/latest.png')
            if not p1.exists():
                with p1.open ('w') as dummy:
                    dummy.write('empty')
            w1=inmgr.add_watch(str(p1), flags.CLOSE_WRITE)
            print('watch is %d' % w1)
            ts=time.time()
            try:
                while True:
                    events = inmgr.read()
                    print('at %6.2f' % (time.time()-ts))
                    for event in events:
                        print('    ', event)
                        for flag in flags.from_mask(event.mask):
                            print('      ' + str(flag))
                            if flag is flags.IGNORED:
                                 print('Naughty!!!')
                                 w1=inmgr.add_watch(p1, flags.CLOSE_WRITE)
            except KeyboardInterrupt:
                print('Stop me now!')
                pass
            finally:
                inmgr.close()

**Comment by chrisjbillington** [comment]
I can't reproduce this.

If I simply `echo foo >> latest.png` I see a single `CLOSE_WRITE` event.

If I for example `echo foo >> latest.png.tmp && mv latest.png.tmp latest.png`, then I see a single `IGNORED` event.

What is doing the writing of the file? If you write to the file yourself (e.g. `echo foo >> latest.png`), do you see both events as well?

I would say it looks like whatever is writing to the file is probably deleting and recreating the file on disk (but for some reason, also opening the original file in write-mode prior to that). You can check if the inode of the file has changed with `ls -li latest.png`. I would bet that it has!

**Comment by pootle** [comment]
Ah! lack of imagination on my part - quite right. I was using bluefish to edit the file and it is a bit strange. nano writing just re-writes the file.
