### ISSUE TITLE
Closing the object does not exit the read()

### ISSUE THREAD

**Issue by jmlemetayer** [chrisjbillington/inotify_simple#30]
Hi,

I am trying to gracefully exit the `inotify.read()` function by calling `inotify.close()`. This does not seem to work.

The workaround is not to use infinite blocking and to set a timeout but this is CPU intensive.

Any tips on how to do this properly ? Thanks

**Comment by wshubert** [comment]
What I do is set a termination wakeup. That is, in addition to the files/directories that you care about, you create a file "DELETE_TO_STOP" and monitor it for the self_delete flag. Then when you want the inotify to stop, you delete that file; if DELETE_TO_STOP is the cause of the wakeup, then you know it's time to call inotify.close() and return.
