### ISSUE TITLE
_libc_call interpret errno=0 as OSError, why?

### ISSUE THREAD

**Issue by ampresent** [chrisjbillington/inotify_simple#7]
I failed to rm_watcher so I follow up here:

	  def _libc_call(function, *args):
	      """Wrapper which raises errors and retries on EINTR."""
	      while True:
	          rc = function(*args)
	          if rc == -1:
	              errno = _libc.__errno_location().contents.value
	              if errno  == EINTR:
	                  # retry
	                  continue
	              else:
	                 raise OSError(errno, os.strerror(errno))
	          return rc

It seems `rc` is -1, and `errno` is 0.
I think `errno==0` means there's no error, also `os.strerror(errno)` tells me it's a success call.
So why did I get an OSError?

**Comment by ampresent** [comment]
It indeed failed, it just didn't set the errno.

**Comment by chrisjbillington** [comment]
Thanks for the report!

If you could give me an example where an inotify function call failed but didn't set the errno, I'd be interested to hear about it! I am not aware of these cases and am under the impression that inotify_simple is using errno correctly, but if I am wrong about this I would definitely want to fix it.

**Comment by chrisjbillington** [comment]
This was fixed in inotify_simple 1.3.3
