### ISSUE TITLE
recursive monitoring

### ISSUE THREAD

**Issue by nonameaccount** [chrisjbillington/inotify_simple#9]
After reviewing the information here on GitHub and the linked wiki, I couldn't make out how to recursively monitor a given path. With the traditional inotifywait, the -r option will watch children of the parent directory. I need to watch a root folder and all subfolders for activity and then perform a rename of a given file when it's closed. I've successfully used your package to accomplish this at the root level, but subdirectories do not work. Is this functionality available or has my ignorance blinded me?

Thanks

**Comment by chrisjbillington** [comment]
Something like this should do the trick:

```python
from inotify_simple import INotify, flags, masks
import os

def recursively_watch(inotify, root_folder, flags):
    """Recursively watch all files and directories under the given root folder, not
    following links. Returns a dictionary that maps watch descriptors to filepaths."""
    watches = {}
    for folder, _, filenames in os.walk(root_folder):
        filepaths = [os.path.join(folder, filename) for filename in filenames]
        for path in [folder] + filepaths:
            try:
                wd = inotify.add_watch(path, flags)
                watches[wd] = path
            except FileNotFoundError:
                # Broken link or deleted
                pass
    return watches


inotify = INotify()
watches = recursively_watch(inotify, '.', masks.ALL_EVENTS)

while True:
    for event in inotify.read():
        print(event)
        for flag in flags.from_mask(event.mask):
            print('    ' + str(flag))
```

Inotify itself does not include any facility for recursively watching folder structures, this functionality in inotifywait is implemented by that tool presumably by manually walking the folder hierarchy in the same manner as the above code. 

Note that this kind of thing is subject to various race conditions and other issues. Folders created after the watch is started will not be watched - unless you are watching for folder creation events and calling `recursively_watch()` on each new folder. If a folder is moved, I think there is also a potential issue whereby it is still watched even though it is no longer a subfolder of the original root folder. Unless of course you are watching for move events and responding to them to keep your watches in sync. It's a tricky problem that I've not attempted to solve with this library, which merely wraps inotify as-is. But the above simple code may be enough for your use case if your code is not affected by the sorts of issues that exist.
